language: python
sudo: true

python:
    - 3.8.2

services:
    - postgresql
addons:
    postgresql: '9.6'

env:
    global:
        - PIPENV_VENV_IN_PROJECT=1
        - PIPENV_IGNORE_VIRTUALENVS=1

install:
    - pip install pipenv
    - pipenv sync -d
    
before_script:
    - psql -c "CREATE DATABASE testdb;" -U postgres

script:
    - pipenv run flake8

