version: "3.3"

services: 
    database:
        container_name: loan_service_database
        image: postgres:11.5
        restart: always
        volumes:
            - ./.pgdata:/var/lib/postgresql/data
        environment:
            - LC_ALL=C.UTF-8
            - POSTGRES_PASSWORD=abg
            - POSTGRES_USER=abg

        ports:
            - 5434:5432