# Generated by Django 3.0.8 on 2020-07-05 04:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('cpf', models.CharField(max_length=11)),
                ('birthdate', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('terms', models.IntegerField()),
                ('income', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
